### ISSUE TITLE
Where do fonts and fontawesome go

### ISSUE THREAD

**Issue by woodbrearlham** [michaelschwobe/gulp-nunjucks-boilerplate#1]

**Comment by michaelschwobe** [comment]
Cloud hosted fonts just require you to add link and/or script tags to your template... I assume you mean to self-host?

If so, you could either [A] update `gulpfile.js` to handle your specific use case or [B] put your font files in `src/public/static/fonts` and then import them in your stylesheet using `@font-face`. Make sure to replace `__FONT_NAME__`, `__FONT_FILENAME__`, and `__FONT_FORMAT__` with your filename and format. You also might need to restart gulp.

```
@font-face {
  /* ...other properties */
  src: url('../fonts/__FONT_FILENAME__') format('__FONT_FORMAT__');
}

/* ...other variables or selectors */
$base-font-family: '__FONT_NAME__', sans-serif !default;

body {
  font-family: $base-font-family;
  /* ...other properties */
}
```

Good luck!
